# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79ab41f2c755eff2fa063c5f4f28a34218bfe101123892a635949b5f031cc62812c4309c44a0b8923351f4b46b85d96f688c77b3c6874be91209918e1f1d26a4

test:
  secret_key_base: 32d25b893df853fbcfb683f89a701704c46d04485b67b6f14dd1b392a3d64958268c1a4301d09780ef478535d1deead79221063c11b67f949acb0ee746fca2bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
